SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT continent FROM `COVID DEATHS`.`covid vaccination`;
SELECT continent, date FROM `COVID DEATHS`.`covid vaccination`;
SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT CONTINENT FROM `COVID DEATHS`.`covid vaccination` WHERE CONTINENT = 'AFRICA';
SELECT * FROM `COVID DEATHS`.`covid vaccination` WHERE CONTINENT = 'AFRICA';
SELECT continent, date FROM `COVID DEATHS`.`covid vaccination` ORDER by date DESC;
SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT continent FROM `COVID DEATHS`.`covid vaccination`;
SELECT continent, date FROM `COVID DEATHS`.`covid vaccination`;
SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT * FROM `COVID DEATHS`.`covid vaccination`;
SELECT CONTINENT FROM `COVID DEATHS`.`covid vaccination` WHERE CONTINENT = 'AFRICA';
SELECT * FROM `COVID DEATHS`.`covid vaccination` WHERE CONTINENT = 'AFRICA';
SELECT COUNT(*) FROM `COVID DEATHS`.`covid vaccination`;
SELECT AVG (median_age) FROM `COVID DEATHS`.`covid vaccination`;
SELECT sum (median_age) FROM `COVID DEATHS`.`covid vaccination`;
SELECT distinct continent, LOCATION FROM `COVID DEATHS`.`covid vaccination` WHERE CONTINENT = 'AFRICA' ORDER BY location DESC;
SELECT COUNT(CONTINENT) FROM `COVID DEATHS`.`covid vaccination` WHERE continent = 'AFRICA';